In [30]:
import sys

import numpy as np

In [39]:
n = 5
a = np.zeros((n, n+1))
x = np.zeros(n)

for i in range(n):
    for j in range(n+1):
        a[i, j] = int(np.random.random() * 10)
        if a[i, j] == 0:
            a[i, j] = int(np.random.random() * 10)

In [40]:
a

array([[7., 8., 4., 6., 3., 5.],
       [5., 3., 3., 8., 4., 3.],
       [5., 8., 1., 4., 2., 3.],
       [5., 2., 3., 6., 2., 6.],
       [2., 7., 4., 4., 7., 1.]])

In [41]:
# Gauss elimination
for i in range(n):
    if a[i, i] == 0:
        sys.exit("Division by zero.")

    for j in range(i+1, n):
        ratio = a[j, i] / a[i, i]

        for k in range(n+1):
            a[j, k] = a[j, k] - ratio * a[i, k]

a

array([[ 7.        ,  8.        ,  4.        ,  6.        ,  3.        ,
         5.        ],
       [ 0.        , -2.71428571,  0.14285714,  3.71428571,  1.85714286,
        -0.57142857],
       [ 0.        ,  0.        , -1.73684211,  2.84210526,  1.42105263,
        -1.05263158],
       [ 0.        ,  0.        ,  0.        , -3.45454545, -2.72727273,
         3.24242424],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         9.66666667]])

In [42]:
# back substitution
x[n-1] = a[n-1, n] / a[n-1, n-1]

for i in range(n-2, -1, -1):
    x[i] = a[i, n]

    for j in range(i+1, n):
        x[i] = x[i] - a[i, j] * x[j]

    x[i] = x[i] / a[i, i]

x

array([13.        , -5.19298246, -5.50877193, -8.57017544,  9.66666667])